### ISSUE TITLE
README Fixes

### ISSUE THREAD

**Issue by rcass** [temefleet/Inhabitent#1]
Great work so far, there are some README changes I thought I would point out so you don't forget about them!

- [x] Create a README.md for your project (so this will be in the root of your project, aka the root of wp-content)

- [x] Modify the Theme readme. There is a readme file in the theme, it currently just has the placeholder text. So be sure to update this before handing it in.

- [x] Modify the Plugin readme. There is a readme file in the plugin, just has placeholder text, so be sure to update it.

Let me know if you have any questions! 👍  good job so far!

**Comment by temefleet** [comment]
Created Readme's. Thanks!

**Comment by rcass** [comment]
In your two custom plugins, they still have the default READMEs so just need to change those from the default! 👍

**Comment by rcass** [comment]
Your main project README look very good 💯

**Comment by temefleet** [comment]
Ah didn't notice that intense readme. Now it's done :) or maybe I should do
the same for Inhabitent Functionality as I did for Business Hours Widget.
Anyways, not tonight.
