### ISSUE TITLE
Namespacing on excerpt_more function

### ISSUE THREAD

**Issue by rcass** [temefleet/Inhabitent#3]
Great job figuring out how to modify the read more for the excerpt.

The function that is being called with the filter can improved by just tweaking the function name.
Since this function is only for the inhabitant theme, I would namespace the function to something like this 'function inhabitent_excerpt_more'

Namespacing will prevent naming collisions, that could occur if you name something too general. It also improved the readability!

- [x] Namespace the new_excerpt_more function (change the name to something a little more descriptive)

**Comment by temefleet** [comment]
Fixed. Thanks!

**Comment by rcass** [comment]
Also looks great! 👍
